package com.hsw.model;
// Generated 07.10.2015 21:18:52 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "Comment", catalog = "ticketverwaltung")
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private String comment;
	private String commentIssuer;
	private Ticket ticket;

	public Comment() {
	}

	public Comment(String comment, String commentIssuer, Ticket ticket) {
		this.comment = comment;
		this.commentIssuer = commentIssuer;
		this.ticket = ticket;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Comment_ID", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@Column(name = "Comment", nullable = false, length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "Comment_Issuer", nullable = false, length = 40)
	public String getCommentIssuer() {
		return this.commentIssuer;
	}

	public void setCommentIssuer(String commentIssuer) {
		this.commentIssuer = commentIssuer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ 
	@JoinColumn(name = "project_code", referencedColumnName="project_code", nullable = false),
	@JoinColumn(name = "ticket_id", referencedColumnName="ticket_name", nullable = false)
	})
	public Ticket getTicket() {
		return ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}
	
	

}
