package com.hsw.model;
// Generated 06.10.2015 23:10:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", catalog = "ticketverwaltung", uniqueConstraints = @UniqueConstraint(columnNames = "Project_Name") )
public class Project implements java.io.Serializable {

	private String projectCode;
	private String projectName;
	private String projectOwner;
	private String projectDesc;
	private int projectCounter;

	public Project() {
	}

	public Project(String projectCode, String projectName, String projectOwner, int projectCounter) {
		this.projectCode = projectCode;
		this.projectName = projectName;
		this.projectOwner = projectOwner;
		this.projectCounter = projectCounter;
	}

	public Project(String projectCode, String projectName, String projectOwner, String projectDesc,
			int projectCounter) {
		this.projectCode = projectCode;
		this.projectName = projectName;
		this.projectOwner = projectOwner;
		this.projectDesc = projectDesc;
		this.projectCounter = projectCounter;
	}

	@Id

	@Column(name = "Project_Code", unique = true, nullable = false, length = 5)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	@Column(name = "Project_Name", unique = true, nullable = false, length = 40)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "Project_Owner", nullable = false, length = 40)
	public String getProjectOwner() {
		return this.projectOwner;
	}

	public void setProjectOwner(String projectOwner) {
		this.projectOwner = projectOwner;
	}

	@Column(name = "Project_Desc", length = 40)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "Project_Counter", nullable = false)
	public int getProjectCounter() {
		return this.projectCounter;
	}

	public void setProjectCounter(int projectCounter) {
		this.projectCounter = projectCounter;
	}

}
