package com.hsw.model;
// Generated 01.10.2015 14:24:38 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Right generated by hbm2java
 */
@Entity
@Table(name = "Right", catalog = "ticketverwaltung")
public class Right implements java.io.Serializable {

	private Integer rightId;
	private String rightName;
	private String rightDesc;

	public Right() {
	}

	public Right(String rightName) {
		this.rightName = rightName;
	}

	public Right(String rightName, String rightDesc) {
		this.rightName = rightName;
		this.rightDesc = rightDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Right_ID", unique = true, nullable = false)
	public Integer getRightId() {
		return this.rightId;
	}

	public void setRightId(Integer rightId) {
		this.rightId = rightId;
	}

	@Column(name = "Right_Name", nullable = false, length = 30)
	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	@Column(name = "Right_Desc", length = 100)
	public String getRightDesc() {
		return this.rightDesc;
	}

	public void setRightDesc(String rightDesc) {
		this.rightDesc = rightDesc;
	}

}
