package com.hsw.model;
// Generated 11.10.2015 00:41:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StatusTyp generated by hbm2java
 */
@Entity
@Table(name = "Status_Typ", catalog = "ticketverwaltung")
public class StatusTyp implements java.io.Serializable {

	private String status;
	private String statusDesc;

	public StatusTyp() {
	}

	public StatusTyp(String status) {
		this.status = status;
	}

	public StatusTyp(String status, String statusDesc) {
		this.status = status;
		this.statusDesc = statusDesc;
	}

	@Id

	@Column(name = "Status", unique = true, nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Status_Desc", length = 40)
	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

}
