package com.hsw.model;
// Generated 12.10.2015 15:58:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusTyp generated by hbm2java
 */
@Entity
@Table(name = "status_Typ", catalog = "ticketverwaltung")
public class StatusTyp implements java.io.Serializable {

	private String status;
	private String statusDesc;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public StatusTyp() {
	}

	public StatusTyp(String status) {
		this.status = status;
	}

	public StatusTyp(String status, String statusDesc, Set<Ticket> tickets) {
		this.status = status;
		this.statusDesc = statusDesc;
		this.tickets = tickets;
	}

	@Id

	@Column(name = "status", unique = true, nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Status_Desc", length = 40)
	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTyp")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
