package com.hsw.model;
// Generated 12.10.2015 15:58:50 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "Tag", catalog = "ticketverwaltung")
public class Tag implements java.io.Serializable {

	private String tagName;
	private String tagDesc;

	public Tag() {
	}

	public Tag(String tagName) {
		this.tagName = tagName;
	}

	public Tag(String tagName, String tagDesc) {
		this.tagName = tagName;
		this.tagDesc = tagDesc;
	}

	@Id

	@Column(name = "Tag_Name", unique = true, nullable = false, length = 20)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Column(name = "Tag_Desc", length = 40)
	public String getTagDesc() {
		return this.tagDesc;
	}

	public void setTagDesc(String tagDesc) {
		this.tagDesc = tagDesc;
	}

}
