package com.hsw.model;
// Generated 06.10.2015 23:10:36 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TicketCommentId generated by hbm2java
 */
@Embeddable
public class TicketCommentId implements java.io.Serializable {

	private String projectCode;
	private int ticketId;
	private int commentId;

	public TicketCommentId() {
	}

	public TicketCommentId(String projectCode, int ticketId, int commentId) {
		this.projectCode = projectCode;
		this.ticketId = ticketId;
		this.commentId = commentId;
	}

	@Column(name = "Project_Code", nullable = false, length = 5)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	@Column(name = "Ticket_ID", nullable = false)
	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "Comment_ID", nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketCommentId))
			return false;
		TicketCommentId castOther = (TicketCommentId) other;

		return ((this.getProjectCode() == castOther.getProjectCode()) || (this.getProjectCode() != null
				&& castOther.getProjectCode() != null && this.getProjectCode().equals(castOther.getProjectCode())))
				&& (this.getTicketId() == castOther.getTicketId()) && (this.getCommentId() == castOther.getCommentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectCode() == null ? 0 : this.getProjectCode().hashCode());
		result = 37 * result + this.getTicketId();
		result = 37 * result + this.getCommentId();
		return result;
	}

}
