package com.hsw.model;
// Generated 06.10.2015 15:00:23 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TicketComment generated by hbm2java
 */
@Entity
@Table(name = "Ticket_Comment", catalog = "ticketverwaltung")
public class TicketComment implements java.io.Serializable {

	private TicketCommentId id;

	public TicketComment() {
	}

	public TicketComment(TicketCommentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "commentId", column = @Column(name = "Comment_ID", nullable = false) ),
			@AttributeOverride(name = "ticketId", column = @Column(name = "TicketID", nullable = false) ) })
	public TicketCommentId getId() {
		return this.id;
	}

	public void setId(TicketCommentId id) {
		this.id = id;
	}

}
