package com.hsw.model;
// Generated 06.10.2015 15:00:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "Ticket", catalog = "ticketverwaltung")
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private String ticketName;
	private String ticketDesc;
	private int projectId;
	private String ticketIssuer;
	private String ticketAuthor;
	private int ticketStatus;

	public Ticket() {
	}

	public Ticket(String ticketName, int projectId, String ticketIssuer, String ticketAuthor, int ticketStatus) {
		this.ticketName = ticketName;
		this.projectId = projectId;
		this.ticketIssuer = ticketIssuer;
		this.ticketAuthor = ticketAuthor;
		this.ticketStatus = ticketStatus;
	}

	public Ticket(String ticketName, String ticketDesc, int projectId, String ticketIssuer, String ticketAuthor,
			int ticketStatus) {
		this.ticketName = ticketName;
		this.ticketDesc = ticketDesc;
		this.projectId = projectId;
		this.ticketIssuer = ticketIssuer;
		this.ticketAuthor = ticketAuthor;
		this.ticketStatus = ticketStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TicketID", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "Ticket_Name", nullable = false, length = 40)
	public String getTicketName() {
		return this.ticketName;
	}

	public void setTicketName(String ticketName) {
		this.ticketName = ticketName;
	}

	@Column(name = "Ticket_Desc", length = 150)
	public String getTicketDesc() {
		return this.ticketDesc;
	}

	public void setTicketDesc(String ticketDesc) {
		this.ticketDesc = ticketDesc;
	}

	@Column(name = "Project_ID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "Ticket_Issuer", nullable = false, length = 40)
	public String getTicketIssuer() {
		return this.ticketIssuer;
	}

	public void setTicketIssuer(String ticketIssuer) {
		this.ticketIssuer = ticketIssuer;
	}

	@Column(name = "Ticket_Author", nullable = false, length = 40)
	public String getTicketAuthor() {
		return this.ticketAuthor;
	}

	public void setTicketAuthor(String ticketAuthor) {
		this.ticketAuthor = ticketAuthor;
	}

	@Column(name = "Ticket_Status", nullable = false)
	public int getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(int ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

}
