package com.hsw.model;
// Generated 12.10.2015 15:58:50 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TicketTag generated by hbm2java
 */
@Entity
@Table(name = "Ticket_Tag", catalog = "ticketverwaltung")
public class TicketTag implements java.io.Serializable {

	private TicketTagId id;
	private Ticket ticket;

	public TicketTag() {
	}

	public TicketTag(TicketTagId id, Ticket ticket) {
		this.id = id;
		this.ticket = ticket;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectCode", column = @Column(name = "Project_Code", nullable = false, length = 5) ),
			@AttributeOverride(name = "ticketId", column = @Column(name = "Ticket_ID", nullable = false) ),
			@AttributeOverride(name = "tagName", column = @Column(name = "Tag_Name", nullable = false, length = 20) ) })
	public TicketTagId getId() {
		return this.id;
	}

	public void setId(TicketTagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "Project_Code", referencedColumnName = "project_code", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Ticket_ID", referencedColumnName = "Ticket_ID", nullable = false, insertable = false, updatable = false) })
	public Ticket getTicket() {
		return this.ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}

}
