package com.hsw.model;
// Generated 07.10.2015 21:18:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "Ticket", catalog = "ticketverwaltung")
public class Ticket implements java.io.Serializable {

	private TicketId id;
	private String ticketName;
	private User ticketIssuer;
	private User ticketAuthor;
	private String ticketDesc;
	private StatusTyp ticketStatus;
	private int ticketPriorität;
	private Project project;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Ticket() {
	}

	public Ticket(TicketId id, String ticketName, User ticketAuthor, StatusTyp ticketStatus, int ticketPriorität, Project project) {
		this.id = id;
		this.ticketName = ticketName;
		this.ticketAuthor = ticketAuthor;
		this.ticketStatus = ticketStatus;
		this.ticketPriorität = ticketPriorität;
		this.project = project;
	}

	public Ticket(TicketId id, String ticketName, User ticketIssuer, User ticketAuthor, String ticketDesc,
			StatusTyp ticketStatus, int ticketPriorität, Project project, Set<Comment> comments) {
		this.id = id;
		this.ticketName = ticketName;
		this.ticketIssuer = ticketIssuer;
		this.ticketAuthor = ticketAuthor;
		this.ticketDesc = ticketDesc;
		this.ticketStatus = ticketStatus;
		this.ticketPriorität = ticketPriorität;
		this.project = project;
		this.comments = comments;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectCode", column = @Column(name = "Project_Code", nullable = false, length = 5) ),
			@AttributeOverride(name = "ticketId", column = @Column(name = "Ticket_ID", nullable = false) ) })
	public TicketId getId() {
		return this.id;
	}

	public void setId(TicketId id) {
		this.id = id;
	}

	@Column(name = "Ticket_Name", nullable = false, length = 40)
	public String getTicketName() {
		return this.ticketName;
	}

	public void setTicketName(String ticketName) {
		this.ticketName = ticketName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticket_issuer", nullable = false)
	public User getTicketIssuer() {
		return this.ticketIssuer;
	}

	public void setTicketIssuer(User ticketIssuer) {
		this.ticketIssuer = ticketIssuer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticket_author", nullable = false)
	public User getTicketAuthor() {
		return this.ticketAuthor;
	}

	public void setTicketAuthor(User ticketAuthor) {
		this.ticketAuthor = ticketAuthor;
	}

	@Column(name = "Ticket_Desc", length = 200)
	public String getTicketDesc() {
		return this.ticketDesc;
	}

	public void setTicketDesc(String ticketDesc) {
		this.ticketDesc = ticketDesc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	public StatusTyp getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(StatusTyp ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

	@Column(name = "Ticket_Priorität", nullable = false)
	public int getTicketPriorität() {
		return this.ticketPriorität;
	}

	public void setTicketPriorität(int ticketPriorität) {
		this.ticketPriorität = ticketPriorität;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_code", nullable = false)
	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Ticket")
	public Set<Comment> getComments() {
		return comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}
	
	
	
	

}
