package com.hsw.model;
// Generated 01.10.2015 14:24:38 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TicketTagId generated by hbm2java
 */
@Embeddable
public class TicketTagId implements java.io.Serializable {

	private int tagId;
	private int ticketId;

	public TicketTagId() {
	}

	public TicketTagId(int tagId, int ticketId) {
		this.tagId = tagId;
		this.ticketId = ticketId;
	}

	@Column(name = "Tag_ID", nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	@Column(name = "TicketID", nullable = false)
	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketTagId))
			return false;
		TicketTagId castOther = (TicketTagId) other;

		return (this.getTagId() == castOther.getTagId()) && (this.getTicketId() == castOther.getTicketId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTagId();
		result = 37 * result + this.getTicketId();
		return result;
	}

}
