package com.hsw.model;
// Generated 01.10.2015 14:24:38 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TicketTag generated by hbm2java
 */
@Entity
@Table(name = "Ticket_Tag", catalog = "ticketverwaltung")
public class TicketTag implements java.io.Serializable {

	private TicketTagId id;

	public TicketTag() {
	}

	public TicketTag(TicketTagId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tagId", column = @Column(name = "Tag_ID", nullable = false) ),
			@AttributeOverride(name = "ticketId", column = @Column(name = "TicketID", nullable = false) ) })
	public TicketTagId getId() {
		return this.id;
	}

	public void setId(TicketTagId id) {
		this.id = id;
	}

}
