package com.hsw.model;
// Generated 11.10.2015 00:41:08 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "ticketverwaltung")
public class Ticket implements java.io.Serializable {

	private TicketId id;
	private Role role;
	private User userByTicketIssuer;
	private User userByTicketAuthor;
	private String ticketName;
	private String ticketDesc;
	private String ticketStatus;
	private int ticketPriorität;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<TicketTag> ticketTags = new HashSet<TicketTag>(0);

	public Ticket() {
	}

	public Ticket(TicketId id, Role role, User userByTicketAuthor, String ticketName, String ticketStatus,
			int ticketPriorität) {
		this.id = id;
		this.role = role;
		this.userByTicketAuthor = userByTicketAuthor;
		this.ticketName = ticketName;
		this.ticketStatus = ticketStatus;
		this.ticketPriorität = ticketPriorität;
	}

	public Ticket(TicketId id, Role role, User userByTicketIssuer, User userByTicketAuthor, String ticketName,
			String ticketDesc, String ticketStatus, int ticketPriorität, Set<Comment> comments,
			Set<TicketTag> ticketTags) {
		this.id = id;
		this.role = role;
		this.userByTicketIssuer = userByTicketIssuer;
		this.userByTicketAuthor = userByTicketAuthor;
		this.ticketName = ticketName;
		this.ticketDesc = ticketDesc;
		this.ticketStatus = ticketStatus;
		this.ticketPriorität = ticketPriorität;
		this.comments = comments;
		this.ticketTags = ticketTags;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectCode", column = @Column(name = "project_code", nullable = false, length = 40) ),
			@AttributeOverride(name = "ticketId", column = @Column(name = "Ticket_ID", nullable = false) ) })
	public TicketId getId() {
		return this.id;
	}

	public void setId(TicketId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_code", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ticket_Issuer")
	public User getUserByTicketIssuer() {
		return this.userByTicketIssuer;
	}

	public void setUserByTicketIssuer(User userByTicketIssuer) {
		this.userByTicketIssuer = userByTicketIssuer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ticket_Author", nullable = false)
	public User getUserByTicketAuthor() {
		return this.userByTicketAuthor;
	}

	public void setUserByTicketAuthor(User userByTicketAuthor) {
		this.userByTicketAuthor = userByTicketAuthor;
	}

	@Column(name = "Ticket_Name", nullable = false, length = 40)
	public String getTicketName() {
		return this.ticketName;
	}

	public void setTicketName(String ticketName) {
		this.ticketName = ticketName;
	}

	@Column(name = "Ticket_Desc", length = 200)
	public String getTicketDesc() {
		return this.ticketDesc;
	}

	public void setTicketDesc(String ticketDesc) {
		this.ticketDesc = ticketDesc;
	}

	@Column(name = "Ticket_Status", nullable = false, length = 20)
	public String getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(String ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

	@Column(name = "Ticket_Priorität", nullable = false)
	public int getTicketPriorität() {
		return this.ticketPriorität;
	}

	public void setTicketPriorität(int ticketPriorität) {
		this.ticketPriorität = ticketPriorität;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	public Set<TicketTag> getTicketTags() {
		return this.ticketTags;
	}

	public void setTicketTags(Set<TicketTag> ticketTags) {
		this.ticketTags = ticketTags;
	}

}
