package com.hsw.model;
// Generated 06.10.2015 15:00:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "ticketverwaltung")
public class User implements java.io.Serializable {

	private String username;
	private String passwort;
	private String email;
	private String vorname;
	private String nachname;

	public User() {
	}

	public User(String username, String passwort, String email, String vorname, String nachname) {
		this.username = username;
		this.passwort = passwort;
		this.email = email;
		this.vorname = vorname;
		this.nachname = nachname;
	}

	@Id

	@Column(name = "Username", unique = true, nullable = false, length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Passwort", nullable = false, length = 256)
	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	@Column(name = "Email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Vorname", nullable = false, length = 30)
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "Nachname", nullable = false, length = 30)
	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

}
