package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private String comment;
	private String commentIssuer;

	public Comment() {
	}

	public Comment(String comment, String commentIssuer) {
		this.comment = comment;
		this.commentIssuer = commentIssuer;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCommentIssuer() {
		return this.commentIssuer;
	}

	public void setCommentIssuer(String commentIssuer) {
		this.commentIssuer = commentIssuer;
	}

}
