package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private String projectCode;
	private String projectDesc;
	private String projectOwner;

	public Project() {
	}

	public Project(String projectCode, String projectOwner) {
		this.projectCode = projectCode;
		this.projectOwner = projectOwner;
	}

	public Project(String projectName, String projectCode, String projectDesc, String projectOwner) {
		this.projectName = projectName;
		this.projectCode = projectCode;
		this.projectDesc = projectDesc;
		this.projectOwner = projectOwner;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public String getProjectOwner() {
		return this.projectOwner;
	}

	public void setProjectOwner(String projectOwner) {
		this.projectOwner = projectOwner;
	}

}
