package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * Right generated by hbm2java
 */
public class Right implements java.io.Serializable {

	private Integer rightId;
	private String rightName;
	private String rightDesc;

	public Right() {
	}

	public Right(String rightName) {
		this.rightName = rightName;
	}

	public Right(String rightName, String rightDesc) {
		this.rightName = rightName;
		this.rightDesc = rightDesc;
	}

	public Integer getRightId() {
		return this.rightId;
	}

	public void setRightId(Integer rightId) {
		this.rightId = rightId;
	}

	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	public String getRightDesc() {
		return this.rightDesc;
	}

	public void setRightDesc(String rightDesc) {
		this.rightDesc = rightDesc;
	}

}
