package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * RoleRight generated by hbm2java
 */
public class RoleRight implements java.io.Serializable {

	private RoleRightId id;

	public RoleRight() {
	}

	public RoleRight(RoleRightId id) {
		this.id = id;
	}

	public RoleRightId getId() {
		return this.id;
	}

	public void setId(RoleRightId id) {
		this.id = id;
	}

}
