package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * RoleRightId generated by hbm2java
 */
public class RoleRightId implements java.io.Serializable {

	private int rightId;
	private int roleId;

	public RoleRightId() {
	}

	public RoleRightId(int rightId, int roleId) {
		this.rightId = rightId;
		this.roleId = roleId;
	}

	public int getRightId() {
		return this.rightId;
	}

	public void setRightId(int rightId) {
		this.rightId = rightId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleRightId))
			return false;
		RoleRightId castOther = (RoleRightId) other;

		return (this.getRightId() == castOther.getRightId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRightId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
