package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * StatusTyp generated by hbm2java
 */
public class StatusTyp implements java.io.Serializable {

	private Integer statusId;
	private String status;
	private String statusDesc;

	public StatusTyp() {
	}

	public StatusTyp(String status) {
		this.status = status;
	}

	public StatusTyp(String status, String statusDesc) {
		this.status = status;
		this.statusDesc = statusDesc;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

}
