package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private String ticketName;
	private String ticketDesc;
	private int projectId;
	private String ticketIssuer;
	private String ticketAuthor;
	private int ticketStatus;

	public Ticket() {
	}

	public Ticket(String ticketName, int projectId, String ticketIssuer, String ticketAuthor, int ticketStatus) {
		this.ticketName = ticketName;
		this.projectId = projectId;
		this.ticketIssuer = ticketIssuer;
		this.ticketAuthor = ticketAuthor;
		this.ticketStatus = ticketStatus;
	}

	public Ticket(String ticketName, String ticketDesc, int projectId, String ticketIssuer, String ticketAuthor,
			int ticketStatus) {
		this.ticketName = ticketName;
		this.ticketDesc = ticketDesc;
		this.projectId = projectId;
		this.ticketIssuer = ticketIssuer;
		this.ticketAuthor = ticketAuthor;
		this.ticketStatus = ticketStatus;
	}

	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	public String getTicketName() {
		return this.ticketName;
	}

	public void setTicketName(String ticketName) {
		this.ticketName = ticketName;
	}

	public String getTicketDesc() {
		return this.ticketDesc;
	}

	public void setTicketDesc(String ticketDesc) {
		this.ticketDesc = ticketDesc;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getTicketIssuer() {
		return this.ticketIssuer;
	}

	public void setTicketIssuer(String ticketIssuer) {
		this.ticketIssuer = ticketIssuer;
	}

	public String getTicketAuthor() {
		return this.ticketAuthor;
	}

	public void setTicketAuthor(String ticketAuthor) {
		this.ticketAuthor = ticketAuthor;
	}

	public int getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(int ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

}
