package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * TicketCommentId generated by hbm2java
 */
public class TicketCommentId implements java.io.Serializable {

	private int commentId;
	private int ticketId;

	public TicketCommentId() {
	}

	public TicketCommentId(int commentId, int ticketId) {
		this.commentId = commentId;
		this.ticketId = ticketId;
	}

	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketCommentId))
			return false;
		TicketCommentId castOther = (TicketCommentId) other;

		return (this.getCommentId() == castOther.getCommentId()) && (this.getTicketId() == castOther.getTicketId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommentId();
		result = 37 * result + this.getTicketId();
		return result;
	}

}
