package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * TicketTagId generated by hbm2java
 */
public class TicketTagId implements java.io.Serializable {

	private int tagId;
	private int ticketId;

	public TicketTagId() {
	}

	public TicketTagId(int tagId, int ticketId) {
		this.tagId = tagId;
		this.ticketId = ticketId;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TicketTagId))
			return false;
		TicketTagId castOther = (TicketTagId) other;

		return (this.getTagId() == castOther.getTagId()) && (this.getTicketId() == castOther.getTicketId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTagId();
		result = 37 * result + this.getTicketId();
		return result;
	}

}
