package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * TicketTag generated by hbm2java
 */
public class TicketTag implements java.io.Serializable {

	private TicketTagId id;

	public TicketTag() {
	}

	public TicketTag(TicketTagId id) {
		this.id = id;
	}

	public TicketTagId getId() {
		return this.id;
	}

	public void setId(TicketTagId id) {
		this.id = id;
	}

}
