package com.hsw.testmodel;
// Generated 30.09.2015 14:41:58 by Hibernate Tools 4.0.0

/**
 * TicketComment generated by hbm2java
 */
public class TicketComment implements java.io.Serializable {

	private TicketCommentId id;

	public TicketComment() {
	}

	public TicketComment(TicketCommentId id) {
		this.id = id;
	}

	public TicketCommentId getId() {
		return this.id;
	}

	public void setId(TicketCommentId id) {
		this.id = id;
	}

}
